spring:
  application:
    name: mscartoes
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

#A port 0 é uma porta randomica, isso server para não termos que subir na mão cada porta
#Gerar as instancias em portas aleatórias
server:
  port: 0

#Qual servidor eureka quero me registrar:
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value} }

mq:
  queues:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/log-file.log